title: Pretesh Mistry
description: Professional software developer, not so professional cupcake maker
author: Pretesh Mistry
lang: en
theme: minima
show_excerpts: true
google_analytics: UA-138045233-1
header_pages:
  - portfolio.md
  - contact.md

minima:
  date_format: "%-d %b %Y"
  social_links:
    github: teshio

github_username: teshio
#linkedin_username: pretesh-j-mistry
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

disqus:
  shortname: preteshmistry-co-uk
